# Colors (Everforest Light)

# Default colors
[colors.primary]
background = '#fdf6e3'
foreground = '#657b83'

# Normal colors
[colors.normal]
black   = '#5c6a72'
red     = '#f85552'
green   = '#00dd00'
yellow  = '#dfa000'
blue    = '#0000ff'
magenta = '#df69ba'
cyan    = '#aa8c00'
white   = '#e0dcc7'

# Bright Colors
[colors.bright]
black   = '#5c6a72'
red     = '#f85552'
green   = '#8da101'
yellow  = '#dfa000'
blue    = '#3aa4e5'
magenta = '#df69ba'
cyan    = '#35a77c'
white   = '#e0dcc7'
